import AppKit
import Foundation

struct JobRowActions {
  let reveal: () -> Void
  let openFirstOutput: () -> Void
  let openArchive: () -> Void
  let openFirstSelectedOutputs: () -> Void
  let viewOutputInBrowser: () -> Void
  let previewOutput: () -> Void
  let createPDF: () -> Void
  let retry: () -> Void
  let directDownload: () -> Void
  let stopLiveRecording: () -> Void
  let pauseAria2: () -> Void
  let resumeAria2: () -> Void
  let applyAria2Limits: () -> Void
  let applyAria2Files: () -> Void
  let applyAria2Seeding: () -> Void
  let previewAria2Files: () -> Void
  let refreshAria2Peers: () -> Void
  let markFinished: () -> Void
  let moveUp: () -> Void
  let moveDown: () -> Void
  let moveOutput: () -> Void
  let deleteJobAndOutput: () -> Void
  let deleteOutput: () -> Void
  let remove: () -> Void
  let copySource: () -> Void
  let copyArtist: () -> Void
  let openSource: () -> Void
  let openAccessHelp: () -> Void
  let info: () -> Void
  let selectForContextMenu: () -> Void
  let edit: () -> Void
  let pages: () -> Void
  let comment: () -> Void
  let togglePin: () -> Void
  let toggleLock: () -> Void
  let pinActionWillPin: () -> Bool
  let lockActionWillLock: () -> Bool
  let canToggleSelectedPins: () -> Bool
  let retryIncomplete: () -> Void
  let clearCompleted: () -> Void
  let isTagChecked: (TaskTagColor) -> Bool
  let toggleTag: (TaskTagColor) -> Void
  let tagName: (TaskTagColor) -> String
  let openTagSettings: () -> Void
  let convertImages: () -> Void
  let moveToGroup: (UUID?) -> Void
  let moveToNewGroup: () -> Void
  let beginReorder: () -> NSPasteboardItem
  let endReorder: () -> Void
  let canBeginReorder: () -> Bool
  let canMoveToGroup: () -> Bool
  let canMoveUp: () -> Bool
  let canMoveDown: () -> Bool
  let canPauseAria2: () -> Bool
  let canResumeAria2: () -> Bool
  let canApplyAria2Limits: () -> Bool
  let canApplyAria2Files: () -> Bool
  let canApplyAria2Seeding: () -> Bool
  let canPreviewAria2Files: () -> Bool
  let canRefreshAria2Peers: () -> Bool
  let canMarkFinished: () -> Bool
  let canOpenPageSelector: () -> Bool
  let canDeleteOutput: () -> Bool
  let canOpenFirstOutput: () -> Bool
  let canOpenFirstSelectedOutputs: () -> Bool
  let canViewOutputInBrowser: () -> Bool
  let canPreviewOutput: () -> Bool
  let canCreatePDF: () -> Bool
  let canDirectDownload: () -> Bool
  let canStopLiveRecording: () -> Bool
  let canMoveOutput: () -> Bool
  let canConvertImages: () -> Bool
  let canCopyArtist: () -> Bool
  let canRetryIncomplete: () -> Bool
  let canClearCompleted: () -> Bool
  let canRevealSelectedOutputs: () -> Bool
  let canDeleteSelectedJobsAndOutput: () -> Bool
  let canRemoveSelectedJobs: () -> Bool
  let canRetrySelectedJobs: () -> Bool
}
